### ISSUE TITLE
使用message组件会自定义主题失效需要添加以下配置

### ISSUE THREAD

**Issue by llf000** [mianmalife/dogdog#8]
AutoImport({
      resolvers: [
        ElementPlusResolver({
          // 自动引入修改主题色添加这一行，使用预处理样式，不添加将会导致使用ElMessage，ElNotification等组件时默认的主题色会覆盖自定义的主题色
          importStyle: "sass",
        }),
      ],
    }),

**Comment by mianmalife** [comment]
yes
